### ISSUE TITLE
Add instructions to auto-start postgres on boot

### ISSUE THREAD

**Issue by Qqwy** [smashedtoatoms/asdf-postgres#15]
I think this would just be `systemctl enable postgresql` for most systems, but it would be helpful to have this in the README for people.

**Comment by smashedtoatoms** [comment]
I’ve deliberately not done it because it’s not really what it was for. There are better ways to install Postgres for permanent usage. This was more meant as a way for devs to use one tool to spin up ephemeral dev dB instances per app. It’s obviously getting used differently than that, and if someone wants to submit a pr on the docs, I’ll put it in, but that’s why it isn’t in there already.
