### ISSUE TITLE
How to configure the default socket location

### ISSUE THREAD

**Issue by Qqwy** [smashedtoatoms/asdf-postgres#25]
Hello everyone! Certain tools (in this case: Ruby on Rails/ActiveRecord/PG) expect Postgres' unix socket location to live in `/run/postgresql/`. I believe that this might have been the default in the past for the ASDF-installed postgres versions as well.

However, currently, this is not the case. According to [what I have found here](https://www.postgresql.org/message-id/21044.1326496507@sss.pgh.pa.us) it seems like when built from source, the default unix socket is placed in `/tmp`.

I would like to configure this behaviour to match the earlier default. How can this be done? And is it possible to document this in this repository? As `asdf` is supposed to be a re-usable 'drop in' replacement for installing a single system-provided binary, I think it would be nice to be able to provide the same kind of behaviour, if not by default then at least as an opt-in possibility.

**Comment by smashedtoatoms** [comment]
I don't think anything has changed in asdf that would affect that.  I am not sure it can be done.  Currently it's set up to allow whatever config is allowed in the build stage to be passed directly through to the build process, so if the build process allows it, then you just need to figure out the flags to pass and pass them.  That link you sent implies people are modifying the source for the distros, which is going to be more than I have time to do.  I also think it's gross.  Maybe something has changed since 2012 to allow it to be configured, but it seems like a big lift.  Rather than try to bend the various distros and postgres community's decisions to our will, I suspect it is easier to just configure rails to look in a different place for the socket.  I think it's literally one line of config.  That's my $0.02.  If anyone wants to try to figure it out I'll consider it for this, but it's beyond what I have time for currently.

**Comment by Qqwy** [comment]
Thank you for your reply!

I think you are right. I am also not entirely sure if this is something `asdf-postgres` should focus on, or if it is something that should be considered by e.g. the postgres team itself.

For my own development experience, I managed a low-effort fix of arguable cleanliness by creating a symlink at `/run/postgresql/.s.PGSQL.5432` to `/tmp/.s.PGSQL.5432`.
