### ISSUE TITLE
postgresql-contrib

### ISSUE THREAD

**Issue by brianbroderick** [smashedtoatoms/asdf-postgres#4]
```
PG::UndefinedFile: ERROR:  could not open extension control file "/Users/myuser/.asdf/installs/postgres/9.6.3/share/extension/uuid-ossp.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
```

I'm getting this error when I try and install the uuid-ossp extension. Googling around suggests that postgresql-contrib needs to be installed. 

How can I install things like postgresql-contrib with asdf?

Thanks.

**Comment by smashedtoatoms** [comment]
Sorry Brian, I just saw this.  So you should be able to run something like `env POSTGRES_EXTRA_CONFIGURE_OPTIONS=--with-uuid=ossp asdf install postgres 9.6.3` and have it install what you're wanting, assuming you have the ossp-uuid libs installed.  I'd recommend not using ossp though, if you have a choice, because I don't think it's maintained any longer.  I don't think it's been updated since 2008, and I have had a hell of a time with it on mac in the past.  I usually use e2fs.  Let me know if that works for you.

**Comment by emilford** [comment]
I tried going down the `--with-uuid=ossp` path, but ran into needing to `brew install ossp-uuid` and then errors about finding ossp header files, but not being able to compile them.

In researching this, I read in several places that discussed abandonment of ossp-uuid and noticed that the homebrew [formula](https://github.com/petere/homebrew-postgresql/blob/master/postgresql%409.6.rb) uses `--with-uuid=e2fs`. I `brew uninstall ossp-uuid` and then was able to run `POSTGRES_EXTRA_CONFIGURE_OPTIONS=--with-uuid=e2fs asdf install postgres 9.6.6`.

I wasn't convinced this was going to work, since the Postgres extension is called `uuid-ossp`, but so far this seems to be working just fine for me.

Hope this helps.

**Comment by djcp** [comment]
On ubuntu 16.04, I was able to get `ossp-uuid` working by:
```
sudo apt install libossp-uuid-dev
POSTGRES_EXTRA_CONFIGURE_OPTIONS=--with-uuid=ossp asdf install postgres 10.4
```

`e2fs` worked fine too (surprisingly!) according to @emilford 's instructions with no extra lib installs.

**Comment by st23am** [comment]
Hate to tag onto this but, is there a list of other extensions for `POSTGRES_EXTRA_CONFIGURE_OPTIONS` ? I am getting an error ``` failed: sslmode value "require" invalid when SSL support is not compiled in```  Maybe I just need to add `--with-ssl` ?

**Comment by st23am** [comment]
Coming back for future users the correct configure opt is `POSTGRES_EXTRA_CONFIGURE_OPTIONS=--with-openssl`

**Comment by jc00ke** [comment]
I'd love to see `--with-openssl` as a default, as I went down a rabbit hole with Heroku support trying to figure out why `heroku pg:psql` wouldn't work.

**Comment by kenny-evitt** [comment]
I ran into this but running install with the 'extra options' variable set didn't work:

```
$ POSTGRES_EXTRA_CONFIGURE_OPTIONS=--with-uuid=ossp asdf install postgres 9.4.5
postgres 9.4.5 is already installed
```

I'm guessing I need to `uninstall` it first.

**Comment by smashedtoatoms** [comment]
That particular error does mean that you need to uninstall first.

**Comment by smashedtoatoms** [comment]
> I'd love to see `--with-openssl` as a default, as I went down a rabbit hole with Heroku support trying to figure out why `heroku pg:psql` wouldn't work.

The only reason I haven't done this is openssl always ends up being a nightmare in and of itself.  I am certainly willing to try it out if folks thing it would be beneficial.

**Comment by kenny-evitt** [comment]
@smashedtoatoms After re-installing, I can't connect via `psql`:

```
$ psql -d postgres
psql: FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory
```

**Comment by kenny-evitt** [comment]
@smashedtoatoms Maybe my shims are messed-up?:

```
$ pg_ctl status
pg_ctl: no server running
$ /home/kenny/.asdf/installs/postgres/9.4.5/bin/pg_ctl status
pg_ctl: no database directory specified and environment variable PGDATA unset
Try "pg_ctl --help" for more information.
```

**Comment by kenny-evitt** [comment]
@smashedtoatoms Sorry for the notifications spam! I seem to have fixed the problem by `kill`-ing the errant `postgres` process and then restarting via `pg_ctl ... start`.

**Comment by smashedtoatoms** [comment]
Sweet, no problem at all.  I am stoked it worked.  I honestly made this plugin for myself ages ago and never thought anyone would use it other than me, so seeing it take on the life it has is fascinating to me.

**Comment by kenny-evitt** [comment]
@smashedtoatoms It's very useful! Thanks! And it's really awesome that you respond on GitHub, let alone so quickly; very generous of you.

**Comment by smashedtoatoms** [comment]
Oh man, go through some of the other issues.  I saw one today from almost 2 years ago that I just replied to.  I don't know how I missed it.  That guy has had a different experience.  I am appropriately ashamed though.

**Comment by jc00ke** [comment]
Ran into this again... is there some testing we can help with to get `--with-openssl` set as the default?

**Comment by smashedtoatoms** [comment]
Yea, it won't be hard to make the default. I just have no idea what it will break.  Let me do it and see if it breaks anything obvious for me.  If it's an easy workaround or doesn't cause any issues I guess we can just do it and see who notices.

**Comment by smashedtoatoms** [comment]
Sorry that this has taken so long to get to.  I am looking at it now, and `--with-openssl` isn't happening as a default until openssl isn't such a ghetto on macs.  I can't get it to build on mac without setting up symlinks to libraries I installed with brew, which is a bridge too far for me.  If anyone has ways to work through `library 'crypto' is required for OpenSSL` that don't require installing openssl and symlinking all over the place, that would be cool, but as it is, if I make that the default, I will end up explaining how to do that every few days here.  Sorry everyone.  I want to be more helpful, but openssl is objectively terrible.

**Comment by earksiinni** [comment]
For anyone coming from the internet using macOS and Homebrew on Apple Silicon, I used the following:

`LDFLAGS="-arch x86_64 -L/usr/local/opt/openssl/lib" CPPFLAGS="-arch x86_64 -I/usr/local/opt/openssl/include" POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-openssl" arch -x86_64 asdf install postgres 11.5`

The `-L/usr/local/opt/openssl/lib` and `-I/usr/local/opt/openssl/include` options point Postgres' configure script to brew's version of OpenSSL, which isn't linked into your default paths because brew doesn't override Apple's version of OpenSSL.

All the `arch -x86_64` stuff is for compiling and linking x86 binaries, which will be executed using Rosetta. I've found that native Apple silicon Postgres is flaky, as of writing. Hopefully this step won't be needed for much longer.
