### ISSUE TITLE
in ubuntu, got error: initdb: error: cannot be run as root 

### ISSUE THREAD

**Issue by sg552** [smashedtoatoms/asdf-postgres#50]
**Describe the bug**

when install postgres in an ubuntu 18.04 LTS, it got error: 

```
make[1]: Entering directory '/tmp/tmp.PtjxQkxbyy/postgresql-12.9/contrib/uuid-ossp'
/bin/mkdir -p '/root/.asdf/installs/postgres/12.9/lib'
/bin/mkdir -p '/root/.asdf/installs/postgres/12.9/share/extension'
/bin/mkdir -p '/root/.asdf/installs/postgres/12.9/share/extension'
/usr/bin/install -c -m 755  uuid-ossp.so '/root/.asdf/installs/postgres/12.9/lib/uuid-ossp.so'
/usr/bin/install -c -m 644 ./uuid-ossp.control '/root/.asdf/installs/postgres/12.9/share/extension/'
/usr/bin/install -c -m 644 ./uuid-ossp--1.1.sql ./uuid-ossp--1.0--1.1.sql ./uuid-ossp--unpackaged--1.0.sql  '/root/.asdf/installs/postgres/12.9/share/extension/'
make[1]: Leaving directory '/tmp/tmp.PtjxQkxbyy/postgresql-12.9/contrib/uuid-ossp'
initdb: error: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
```

**Steps to reproduce**

$ asdf install postgres 12.9

**Expected behavior**

successful install

**Screenshots**

![图片](https://user-images.githubusercontent.com/234533/150893072-19638db1-fc84-45b6-aa0e-26192ad62402.png)

**Comment by smashedtoatoms** [comment]
This is not an issue with the plugin, unfortunately.  This is by design in Postgres itself.  You can read the docs [here](https://www.postgresql.org/docs/12/app-initdb.html) for the explanation.  You will likely need to create a user in your docker container.  If you're running in a container, you may find that it's better off to just install Postgres directly into the container instead of using asdf.

**Comment by sg552** [comment]
ok , thanks a lot .
I am not using docker, I am using virtual machine like AWS EC2 instance.

I installed postgres via `apt install` and everything works well.

**Comment by sg552** [comment]
OK, got it, thanks!
