### ISSUE TITLE
Can't find log file

### ISSUE THREAD

**Issue by samsondav** [smashedtoatoms/asdf-postgres#60]
Where is the log file?

**Comment by smashedtoatoms** [comment]
Hi, I am so sorry I missed this.  I have somehow borked my github notifications and am not getting emails.  

In any case, the installation and operation provided by this installer is completely bare-bones by design.  Postgres logs to stderr by default, so if you don't specify it on the command line or in a config file, that's what it will do.  The instructions for configuring it can be found here [here](https://www.postgresql.org/docs/current/runtime-config-logging.html).  

Here is an example of how you might start it and write a log file to the directory you are in when you start it.
```sh
pg_ctl -D ~/.asdf/installs/postgres/14.4/data -l logfile stop
```
