### ISSUE TITLE
Install binary packages

### ISSUE THREAD

**Issue by abitrolly** [smashedtoatoms/asdf-postgres#62]
**Is your feature request related to a problem? Please describe.**

Installation of PostreSQL takes a lot of time. 15 minutes min. Because it is compiled from source.

**Describe the solution you'd like**

Install binaries from https://apt.postgresql.org/pub/repos/apt/pool/12/p/postgresql-12/

**Describe alternatives you've considered**

`apt install` as in https://wiki.postgresql.org/wiki/Apt, but it doesn't allow to manage multiple versions.

**Additional context**

https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/1219

**Comment by smashedtoatoms** [comment]
When I originally wrote this plugin it was very early days in the life of asdf.  Asdf was primarily used as a development tool in the spirit of nvm.  It was written for maximum development flexibility.  It was intended to be able to be used in a way that would allow people to set compile flags and customize their installation however they needed to, and run specific versions per project.  Speed and developer ergonomics were not requirements.  I expected that people using this plugin could script whatever conveniences they needed.  People often request automatic startup scripts for it or tooling that normal package managers include.  I generally don't include them because they are outside the scope of this plugin, which is purely for providing minimal configurable dev instances of Postgres.

I am not strictly averse to it having the option to do binary installs; however, it doesn't align with how I use this plugin or originally intended this plugin to be used, so I have never done it.  At a minimum, it would have to detect OS/distro/architecture and install the correct one in the correct place for asdf.  Looking at your case, it would need to support `macOS 12, 11, 10.15, Ubuntu 22.04 (1), 21.10, Fedora 36 (1), 35, Debian 13, 12, Arch latest, Manjaro latest`.  To address your "for some reason" [comment in the issue](https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/1219),  the only reason it works at all right now is because asdf-postgres compiles from source.  There are no Arch/Manjaro builds provided by Postgres.  There are also no Apple ones above Postgres 10 as EDB provides them.  

Installing binaries rapidly becomes a labyrinth of conditionals unless only specific versions of binary installs are supported for specific distros and installed with lots of custom flags.  The moment that is done, I get requests to build for every distro that isn't covered and requests for every custom plugin that exists against every version that exists (the original requirements for this project).  I suspect part of the reason this plugin is being used in your project now is to avoid having to deal with this exact complexity.  The plugin allows you to pin a non-distro-specified instance of Postgres for your exact use case in a way that doesn't cause any conflicts with packages the user already has installed on their system.  Without introducing a bunch of complexity unique to each distro, the only way it can do that that I know of is by installing from the source.

All this to say, if you want to open a PR against this package to add binary installs that meet your minimum requirements: `macOS 12, 11, 10.15, Ubuntu 22.04 (1), 21.10, Fedora 36 (1), 35, Debian 13, 12, Arch latest, Manjaro latest` that doesn't disrupt the distro's current installs, I would love to have that as an option.  Maybe it doesn't even need all of that.  Maybe it just needs Ubuntu and Mac and the rest can default to source?  I don't know how exhaustive your testing on different distros is.  I don't have the resources to do it right now, though.  

I am not familiar with your project, so I am hesitant to try to provide any suggestions.  That said, in the short term, it may be easier to cache your ~/.asdf build directory or mount a volume or something to make asdf not have to install from scratch every time in your pipeline.  I know that introduces its own complexities, though.  You're definitely hitting a rough edge of the requirements that I built to as they apply to your use case, and I apologize.  I also apologize for not having the time to solve this for you.  It is more complicated than it seems at a glance, though.

**Comment by abitrolly** [comment]
Thanks for the thorough answer. My previous experience with `asdf` was that it downloaded binaries, so my expectation was that the plugin will download them as well. I also ported some things to Homebrew, and it also allows to install binary bottles. However, as I see it, upstream https://www.postgresql.org/download/ doesn't provide binary downloads for Linux, only packages.

Given that upstream PostgreSQL project doesn't provide any portable binaries, the task of compiling and distributing the binaries is indeed a big endeavor for two men army. I am not dealing with PostgreSQL daily, but if you have connections with upstream, maybe raise the question there?

Saving developer's time directly affects saving money, so for this this issue should be fundable, but I don't have any company behind to back this claims.

I am not familiar with `asdf`, but maybe it already has helpers to extract and install binaries from `.deb` archives, and detect OS version. In any case it would be interesting to know how `asdf` manages to separate binary files to co-exist after they've been built. If there is a list of what should be copied where, maybe I can write an extractor. Well, being realistic, I am unlikely to get to this any time soon, but the idea looks interesting.
