### ISSUE TITLE
Possibility to close currently running postgres even if I don't know in which path I started it before

### ISSUE THREAD

**Issue by alexanderadam** [smashedtoatoms/asdf-postgres#63]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a clean solution to stop the currently running pg server even if I don't know any more where I started it.

If I'm in another project with another version I'm getting

```
pg_ctl: PID file "~/.asdf/installs/postgres/…/data/postmaster.pid" does not exist
Is server running?
```

otherwise

**Describe the solution you'd like**

I don't know whether this is possible but maybe something like `asdf postgres stop` and `asdf postgres restart` which checks for currently running versions first and closes it properly before calling `pg_ctl …`.

**Describe alternatives you've considered**

Killing it the other process not so clean.

**PS:** Thank you so much for asdf postgres!

**Comment by smashedtoatoms** [comment]
This is out of the scope of this project.  There is no way for me to know how a user will want to stop or start the process.  The reason I haven't prescribed one other than the suggested manual way in the docs is that any choice made will be wrong for lots of people.  

In my projects, I write scripts for starting and stopping the DB depending on the use case (for local dev I add a script, for testing I use ephemeral postgres).  Any assumptions I make will be wrong for someone, so I would need to make the whole process overridable to keep it composable.  If people need that kind of tooling, I think a different package manager is probably a better solution since they are more full-featured.

I am sorry I don't have a better answer for this.  I view asdf as a package manager that is deliberately more composable and configurable, but with that freedom comes more burden on the user.
