### ISSUE TITLE
Do not export PGPORT and PGHOST in exec-env

### ISSUE THREAD

**Issue by grncdr** [smashedtoatoms/asdf-postgres#68]
**Is your feature request related to a problem? Please describe.**

I've been using this plugin for a while in a project that uses a local postgres server.
We run postgres with a local datadir and configure it to use port 15432, then have something like this in our application startup:

```
PGPORT=${PGPORT:-"15432"} # default to the project-owned postgres server
```

This has all been working very well for us, but recently I switched from `asdf` to [`rtx`](https://github.com/jdxcode/rtx) which applies the exec-env from the plugin as part of a prompt hook instead of using shims.

This has led to a situation where PGPORT is already set by this plugin inside that project directory, and the port for the project-owned postgres server won't be used.

**Describe the solution you'd like**

Since the script is just exporting values that are _already_ the Postgres defaults, simply removing those exports would solve my issue and shouldn't cause any noticeable change in behaviour.

**Describe alternatives you've considered**

rtx has experimental support for setting arbitrary env variables in an `.rtx.toml` config file, (https://github.com/jdxcode/rtx/pull/241) so I could probably use that to override PGPORT, I don't think it should be required.

**Additional context**

rtx also has experimental shim support (https://github.com/jdxcode/rtx/issues/118), but again, I think it's simpler to just not export those variables from this plugin.

**Comment by smashedtoatoms** [comment]
Ok, this issue is fixed [here](https://github.com/smashedtoatoms/asdf-postgres/commit/fd8d5aa3233baa0d1fa58d48d44bd97b866d9f0f).  My reason for making it is because I was an idiot seven years ago when I added those environment variables and didn't explain why I put them in there.  I have no idea if I needed them or not.  I suspect I cargo-culted them in there.  This is why git commit messages matter.  If a single user complains about this, I will revert it immediately and figure out a less disruptive way to make this change.  Here is my reasoning:

I don't mean this as harshly as it will come across; however, you're using `rtx`, which completely changes the default environment variable behavior from `asdf-vm`, and asking for me to modify the Postgres `asdf-vm` plugin to accommodate your bespoke setup which uses a currently unsupported tool (`rtx`).  It's a pretty unreasonable ask.  

It is 100% on you to figure out how to accommodate the tool change you have made.  `rtx` gave you the escape hatch via [the link you posted](https://github.com/jdxcode/rtx/pull/241).  Actually, the more I read about that one feature, the more it makes me think I will probably switch to `rtx` just for that escape hatch.  It basically eliminates my need to use `direnv`.  You say it's simpler to "just not export those variables."  Simpler for who?  It's pretty simple for every other user of the plugin to continue to have it behave the way it has behaved for the last seven years.  

If I phrase it a different way, you want me to break the contract I have defined and enforced with users for the last seven years to accommodate your application's startup script so that `rtx` will work for you?  I would normally respond with a hard no.  As it is, I have no idea why I put those in.  I think you're totally right that they don't need to be there, and it seems really stupid to leave the mistake in there if it is a mistake.  I don't have tons of time to experiment with it, so I will yank them and see what happens.

If it turns out that it breaks anyone, I will immediately revert it, and write a follow-up mod to add an install setting to create the `exec-env` file dynamically so that people can opt-in to not having those environments set on install.  I don't have a ton of time to sort that out now though, so for now I am going to yeet it and see what happens.  Just be aware that if I have to revert this and do it a different way, this is why.

**Comment by smashedtoatoms** [comment]
Thanks for being so understanding.  So far, no complaints.  It didn't break anything I am doing, so hopefully, I just cargo-culted that in there, and it won't matter.  Is it working for you now?  I will try out `rdx` this weekend and see if it works for me.  If it does, I can get rid of `direnv`.

**Comment by grncdr** [comment]
So far it's working great for me :+1:

I tried to think a bit more in depth about what _could_ go wrong for others, and there's one scenario I can imagine. If somebody wrote a script or tool that they always execute via `asdf env postgres` it _could_ assume PGPORT is set and break without it. I feel like that would be so unergonomic that it's unlikely to happen in practice, but I guess we'll see 😅🤞

**Comment by jdxcode** [comment]
just a note from the maintainer of rtx: I'm currently experimenting with how exec-env behaves in rtx. The current behavior is not ideal for this plugin.

For some context: running `bin/exec-env` every time a shim is called or on every time the user enters a directory causes rtx to slow down massively. Running bash like this for me takes ~3x longer and I don't see a way to optimize it further. This isn't really an issue with asdf because it's just importing bash scripts.

So I want to avoid shelling out to bash. My current solution is to cache these values for the life of an install, so when you run `rtx install postgres@xxx` that will cache the values in `bin/exec-env` forever for that version. This behavior is up for discussion, but I want to see if we can cache as much as possible. It works fine for most plugins, but it won't work well here.

Almost all exec-env scripts that I've seen just use static values that are specific to an install (like `ASDF_INSTALL_PATH`). However messing with `LD_LIBRARY_PATH` as this plugin does _will_ cause problems in rtx since that will be cached globally at the point of install.

A few options:
* We can whitelist postgres to never cache
* We could create a different `bin/exec-env-always` (bad name but you get the idea) script that always runs
* Plugins could contain a configuration file (that I wouldn't need to shell out for) such as `rtx-plugin.toml` with a setting like `exec-env: {cache = false}`

Or possibly the best solution: can we get rid of LD_LIBRARY_PATH? If we start shelling out every time someone enters a directory that's using asdf-postgres in rtx it will cause a small, but notable, performance impact.

I'd like to figure out something soon before too many people rely on whatever behavior we end up using. If you have any other ideas I'm happy to consider them.

**Comment by smashedtoatoms** [comment]
I need to think about it. It would break anyone that is linking to postgres from something else... except that I don't think that can't ever really happen because asdf only evaluates the environment variables when the shimmed commands run.  Let me think about it and see if I can figure out what it might break.
